#!/bin/bash
#
# Barra de estado para i3.
#
# Depende de la máquina. Pobre manzanita
# Bar ya va en PPC. Bye conky! :P

# Para manzanita (ppc) -> conky básico
#if [ $("hostname") == "manzanita" ];  then
#  exec conky -c ~/.i3/conkyrc &
# Los demás -> bar
#else
  exec ~/.i3/bar/i3_bar.sh &
#fi
