#!/bin/bash
#
# IRC highlight warn for weechat
# Add "/exec -bg <path>/irc_warn ${tg_date} ${tg_tag_nick}" in weechat
# beep trigger
#
# No parameters -> Reset highlight

. $(dirname $0)/i3_bar_config

[ ! -e "${panel_fifo}" ] && exit 1

# Reset highlight
if [ $# -eq 0 ]; then
  printf "IRC0\n" > "${panel_fifo}"
else
  # Ignore seconds
  time="$(echo $2 | cut -d':' -f1-2)"
  # Cut large nicks > 8
  if [ "$(echo $3 | wc -m)" -gt 8 ]; then
    nick="$(echo $3 | cut -c 1-8)"
    nick=$nick"+"
  else
    nick="$(echo $3)"
  fi
  printf "%s%s %s\n" "IRC" "${time}" "${nick}" > "${panel_fifo}"
  # Warning
  if [ -x "/usr/bin/aplay" ]; then
    /usr/bin/aplay -q $HOME/.config/sounds/chat.wav &
  fi
fi
